//! lest/core, compiled into this binary and written to `.lest/core` on demand.
//!
//! The framework is not a package the user installs — it ships inside the CLI,
//! so the runner and the framework are always the same version and the
//! protocol can never skew against itself. `.lest/` is generated and normally
//! gitignored, so `ensure` is called from both ends: `lest init` writes the
//! sources eagerly (the example spec it scaffolds must resolve immediately in
//! an editor), and every run rewrites them when they are missing or came from a
//! different build.
//!
//! Specs reach the sources the ordinary way — a require of real `.luau` files —
//! which is what gives them types in Luau-LSP and keeps selene happy with no
//! generated definitions to maintain. `lest init` offers a `.luaurc` alias so
//! that require can be `@lest` instead of a relative path.

use std::path::{Path, PathBuf};

use crate::error::ToolError;

// `EMBEDDED` and `EMBED_DIGEST`, generated by build.rs from luau/core.
include!(concat!(env!("OUT_DIR"), "/core_embed.rs"));

/// Where the framework is written, relative to the project root. Forward
/// slashes: this string also appears in generated `.luaurc` aliases.
pub const CORE_DIR: &str = ".lest/core";

/// Records which build wrote the directory. Compared, not parsed — any
/// difference means rewrite.
const STAMP_FILE: &str = ".stamp";

fn stamp() -> String {
    format!(
        "lest {} {:#018x}\n",
        env!("CARGO_PKG_VERSION"),
        EMBED_DIGEST
    )
}

/// Absolute path to `.lest/core` under `root`. Derived from [`CORE_DIR`] rather
/// than spelled out again, component by component so the forward slashes there
/// become native separators here.
pub fn core_dir(root: &Path) -> PathBuf {
    CORE_DIR
        .split('/')
        .fold(root.to_path_buf(), |path, part| path.join(part))
}

/// Returns the normalized path to the embedded framework's `init.luau`,
/// writing the sources first when they are absent or stale.
pub fn ensure(root: &Path) -> Result<PathBuf, ToolError> {
    let dir = core_dir(root);
    let entry = dir.join("init.luau");
    // A matching stamp says "this build wrote this directory", not "this
    // directory is still intact" — `.lest/` is generated state users delete
    // from freely, and half of it can go while the stamp and init.luau stay.
    // Every run is supposed to repair it, so check that each module is actually
    // there. It is one `is_file` per module against a directory the OS just
    // walked, which is far cheaper than the rewrite it usually avoids.
    let intact = entry.is_file()
        && EMBEDDED.iter().all(|(name, _)| dir.join(name).is_file())
        && std::fs::read_to_string(dir.join(STAMP_FILE))
            .ok()
            .as_deref()
            == Some(&stamp());
    if intact {
        return Ok(crate::resolve::normalize(&entry));
    }
    write(root)?;
    Ok(crate::resolve::normalize(&entry))
}

/// Writes every embedded module to `.lest/core`, replacing whatever was there.
/// Unconditional — `ensure` decides when it is needed.
pub fn write(root: &Path) -> Result<(), ToolError> {
    let dir = core_dir(root);

    // The directory is rebuilt rather than written over so a module dropped
    // from a later version of core cannot linger and keep resolving. Clearing
    // it means deleting files, so refuse unless it is recognizably ours:
    // anything else in `.lest/core` belongs to someone who did not put it
    // there for us.
    if dir.exists() {
        if !dir.is_dir() {
            return Err(ToolError(format!(
                "{} exists but is not a directory — lest needs to write the framework there",
                dir.display()
            )));
        }
        if !dir.join(STAMP_FILE).is_file() && !dir.join("init.luau").is_file() {
            return Err(ToolError(format!(
                "{} already exists and was not written by lest — move it aside, or point \
                 `core` in lest.toml at the framework you want to use",
                dir.display()
            )));
        }
    }

    // The new tree is built in a temp sibling and swapped in, so the
    // observable `.lest/core` is never half-written. Writing modules into it
    // directly meant an interrupt (Ctrl+C mid-write) could leave a directory
    // with neither `.stamp` nor `init.luau` — exactly the shape the refusal
    // above treats as foreign, bricking every later repair.
    //
    // The swap is only atomic-ish: between removing the old directory and the
    // rename there is a window where `.lest/core` is absent, and two lest
    // processes racing here can still collide (one loses the rename). Either
    // state heals on the next run — best effort is enough for generated state.
    let tmp = dir.with_file_name("core.tmp");
    if tmp.exists() {
        // Leftover from an earlier interrupted write.
        std::fs::remove_dir_all(&tmp)
            .map_err(|e| ToolError(format!("cannot clear {}: {e}", tmp.display())))?;
    }
    for (name, source) in EMBEDDED {
        let path = tmp.join(name);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| ToolError(format!("cannot create {}: {e}", parent.display())))?;
        }
        std::fs::write(&path, source)
            .map_err(|e| ToolError(format!("cannot write {}: {e}", path.display())))?;
    }
    std::fs::write(tmp.join(STAMP_FILE), stamp())
        .map_err(|e| ToolError(format!("cannot write the stamp in {}: {e}", tmp.display())))?;

    if dir.exists() {
        std::fs::remove_dir_all(&dir)
            .map_err(|e| ToolError(format!("cannot clear {}: {e}", dir.display())))?;
    }
    std::fs::rename(&tmp, &dir).map_err(|e| {
        ToolError(format!(
            "cannot move {} into place at {}: {e}",
            tmp.display(),
            dir.display()
        ))
    })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embeds_the_framework_entry() {
        assert!(EMBEDDED.iter().any(|(name, _)| *name == "init.luau"));
        // The whole point is that specs get real source to infer types from.
        let (_, init) = EMBEDDED
            .iter()
            .find(|(name, _)| *name == "init.luau")
            .unwrap();
        assert!(init.contains("function Lest.describe"));
    }

    #[test]
    fn ensure_writes_then_reuses() {
        let temp = tempfile::tempdir().unwrap();
        let entry = ensure(temp.path()).unwrap();
        assert!(entry.is_file());
        assert!(core_dir(temp.path()).join(STAMP_FILE).is_file());

        // A second call with a matching stamp must not rewrite: touch a file
        // and confirm it survives.
        let marker = core_dir(temp.path()).join("init.luau");
        std::fs::write(&marker, "-- edited\n").unwrap();
        ensure(temp.path()).unwrap();
        assert_eq!(std::fs::read_to_string(&marker).unwrap(), "-- edited\n");
    }

    #[test]
    fn ensure_rewrites_when_the_stamp_is_stale() {
        let temp = tempfile::tempdir().unwrap();
        ensure(temp.path()).unwrap();
        let init = core_dir(temp.path()).join("init.luau");
        std::fs::write(&init, "-- edited\n").unwrap();
        std::fs::write(core_dir(temp.path()).join(STAMP_FILE), "lest 0.0.0 0x0\n").unwrap();

        ensure(temp.path()).unwrap();
        assert!(std::fs::read_to_string(&init)
            .unwrap()
            .contains("Lest.describe"));
    }

    /// "Every run repairs it" has to mean every module, not just the entry:
    /// deleting one of core's other files left the stamp and `init.luau` in
    /// place, so `ensure` returned happily and the run failed on the require.
    #[test]
    fn ensure_restores_a_module_deleted_from_under_it() {
        let temp = tempfile::tempdir().unwrap();
        ensure(temp.path()).unwrap();

        let victim = EMBEDDED
            .iter()
            .map(|(name, _)| *name)
            .find(|name| *name != "init.luau")
            .expect("core ships more than its entry module");
        let path = core_dir(temp.path()).join(victim);
        std::fs::remove_file(&path).unwrap();

        ensure(temp.path()).unwrap();
        assert!(path.is_file(), "{victim} was not restored");
    }

    #[test]
    fn rewriting_drops_modules_that_are_no_longer_shipped() {
        let temp = tempfile::tempdir().unwrap();
        ensure(temp.path()).unwrap();
        let orphan = core_dir(temp.path()).join("removed.luau");
        std::fs::write(&orphan, "return nil\n").unwrap();

        write(temp.path()).unwrap();
        assert!(!orphan.exists());
    }

    /// The temp sibling from an interrupted write must neither break the next
    /// write nor survive it — and the swap must still produce a complete
    /// `.lest/core` with its stamp.
    #[test]
    fn a_stale_temp_directory_is_cleared_and_replaced() {
        let temp = tempfile::tempdir().unwrap();
        let tmp = core_dir(temp.path()).with_file_name("core.tmp");
        std::fs::create_dir_all(&tmp).unwrap();
        std::fs::write(tmp.join("half.luau"), "-- interrupted\n").unwrap();

        write(temp.path()).unwrap();
        assert!(!tmp.exists(), "the temp directory lingered after the swap");
        assert!(core_dir(temp.path()).join("init.luau").is_file());
        assert!(core_dir(temp.path()).join(STAMP_FILE).is_file());
        assert!(!core_dir(temp.path()).join("half.luau").exists());
    }

    #[test]
    fn refuses_to_clear_a_directory_lest_did_not_write() {
        let temp = tempfile::tempdir().unwrap();
        let dir = core_dir(temp.path());
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("theirs.txt"), "important").unwrap();

        assert!(write(temp.path()).is_err());
        assert!(dir.join("theirs.txt").is_file());
    }
}
